### PR TITLE
watch script + contrib guide

### PR DESCRIPTION
**Pull request by troussej**
Hey JC, I'm submitting this change as a PR, since it adds (optional) npm dependencies to the project , you might wait to weigh on this ;) 

Basically just adds a gulp watch script, nothing fancy. One thing that bothers me in the script is that, since sources are directly at the root the project, new folders must be added at in the gulp script manually. But moving everything to a /src folder opens up a whole new can of worms...

### CODE REVIEW

**Comment by jc7447** [comment]
Looks good, I'm not used to Gulp but I will probably give it a try ;)

Regarding a src folder, it's indeed difficult since the root folder is today a src folder but also the "release" folder from where the script is installed. From now, it has been simple and efficient, if it becomes inappropriate with new dev tools in the future, we should move to a more complex structure.

**Comment by troussej** [comment]
Yeah a src and dist folders would be cleaner. I'm also playing with the
idea of writing some new features in typescript, a build system would be
required.

**Comment by troussej** [comment]
JC, this was merged in master, but dev is lagging behind... should we just pull a new dev from master?

**Comment by jc7447** [comment]
I just merged master into develop, they are even now

**Pull request merged**
